/* مبادئ شبكات الحاسب — service worker (offline cache) */
const CACHE='nets-3-ed276e0d';
const ASSETS=["./", "assets/app.css", "assets/app.js", "assets/base.css", "assets/fonts.css", "assets/fonts/cairo-arabic-500-normal.woff2", "assets/fonts/cairo-arabic-600-normal.woff2", "assets/fonts/cairo-arabic-700-normal.woff2", "assets/fonts/cairo-arabic-800-normal.woff2", "assets/fonts/cairo-arabic-900-normal.woff2", "assets/fonts/cairo-latin-500-normal.woff2", "assets/fonts/cairo-latin-600-normal.woff2", "assets/fonts/cairo-latin-700-normal.woff2", "assets/fonts/cairo-latin-800-normal.woff2", "assets/fonts/cairo-latin-900-normal.woff2", "assets/fonts/tajawal-arabic-400-normal.woff2", "assets/fonts/tajawal-arabic-500-normal.woff2", "assets/fonts/tajawal-arabic-700-normal.woff2", "assets/fonts/tajawal-arabic-800-normal.woff2", "assets/fonts/tajawal-latin-400-normal.woff2", "assets/fonts/tajawal-latin-500-normal.woff2", "assets/fonts/tajawal-latin-700-normal.woff2", "assets/fonts/tajawal-latin-800-normal.woff2", "assets/guard.js", "assets/home.js", "assets/practice-u1.js", "assets/practice-u2.js", "assets/practice-u3.js", "assets/practice-u4.js", "assets/practice-u5.js", "assets/practice.js", "assets/unit-app.js", "icons/apple-touch-icon.png", "icons/favicon-64.png", "icons/icon-192.png", "icons/icon-512.png", "icons/maskable-512.png", "index.html", "manifest.webmanifest", "practice-u1.html", "practice-u2.html", "practice-u3.html", "practice-u4.html", "practice-u5.html", "u1.html", "u2.html", "u3.html", "u4.html", "u5.html", "اقرأني - خطوات النشر.txt"];
self.addEventListener('install',e=>{ e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())); });
self.addEventListener('activate',e=>{ e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())); });
self.addEventListener('fetch',e=>{
  const r=e.request; if(r.method!=='GET') return; const u=new URL(r.url); if(u.origin!==location.origin) return;
  e.respondWith(caches.match(r,{ignoreSearch:true}).then(hit=>hit||fetch(r).then(res=>{ if(res.ok&&res.type==='basic'){ const cp=res.clone(); caches.open(CACHE).then(c=>c.put(r,cp)); } return res; }).catch(()=>r.mode==='navigate'?caches.match('index.html'):undefined)));
});
